# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5ae4b8247b736bf9ae9a85bbeb8a3edef3527a7f4a2864d3224f45537988a125aabf2ed980e34729c2339471b6fa92020ddaa6430e258ebeabd6707765ab357

test:
  secret_key_base: 53f3bf8006fdaf6a4e7f3722dbb14159b068fdac612028c44b0e7790e7449a46c06d77dbac1ab0ad87b03268eccc207efb994398564e1b9b2d47228cf4bce536

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
